collab/urls.py
from django.urls import path
from .views import *

app_name = 'collab'

urlpatterns = [
    path('all-clubs/', ListClubsView.as_view(), name='all_clubs'),
    path('create-club/', CreateClubView.as_view(), name='create_club'),
    path('profile-user/', ProfileUser.as_view(), name='profile_user'),
    path('detail-club/<slug:slug>/', DetailClubView.as_view(), name='detail_club'),
    path('join-club/<slug:slug>/', join_club_view, name='join_club'),
    path('send-msg/<slug:slug>/<int:pk>/', SendMsgView.as_view(), name='send_msg'),
    # for author club only
    path('list-confirm-team/<slug:slug>/', ListRequestTeamView.as_view(), name='list_confirm_team'),
]

projectclubs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('users/', include('users.urls')),
    path('', include('collab.urls')),
]

urlpatterns += debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', RegisterUserView.as_view(), name='signup'),
    path('api/v1/user-data/<slug:verif_code>/', UserDataAPIViewVerificationCode.as_view(), name='api_user_data'),
]

collab/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django_ckeditor_5.fields import CKEditor5Field


class ClubModel(models.Model):
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='slug', null=True, blank=True)
    name = models.CharField(max_length=255, verbose_name='Название', unique=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                               verbose_name='Автор', related_name='author_club_model')
    desc = models.TextField(verbose_name='Краткое описание')
    tags = TaggableManager()
    text = CKEditor5Field('Полное описание', config_name='extends', null=True, blank=True)
    required_team = models.TextField(verbose_name='Требуются в команду', null=True, blank=True)
    request_team = models.ManyToManyField(get_user_model(), verbose_name='Заявки на участие',
                                          blank=True, related_name='request_team_club_model')

    valid_team = models.ManyToManyField(get_user_model(), verbose_name="Участники клуба",
                                        blank=True, related_name='valid_team_club_model')

    class Meta:
        verbose_name_plural = 'Clubs'

    def get_absolute_url(self):
        return reverse('collab:detail_club', kwargs={'slug': self.slug})

    def parts_with_tags(self):
        # for tag in club.tags.all.prefetch_related
        return self.tags.select_related('tag')

    def __str__(self):
        return self.name

collab/forms.py
from django import forms
from .models import *
from django_ckeditor_5.widgets import CKEditor5Widget


class ClubModelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["text"].required = False

    class Meta:
        model = ClubModel
        fields = ['name', 'desc', 'tags', 'text', 'required_team']



class SendMsgForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea)

collab/views.py
import asyncio

from django.shortcuts import render, redirect
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, TemplateView, DetailView, FormView

from projectclubs.settings import admin_chat_id
from .models import *
from .forms import *
from .tbot_utils import send_message_to_user
from django.http import Http404

from .utils import *


# Вывод всех клубов.
class ListClubsView(ListView):
    model = ClubModel
    template_name = 'collab/all_clubs.html'
    context_object_name = 'all_clubs'
    extra_context = {
        'title': 'Клубы',
        'menu_slug': 'all_clubs'
    }


# Детальное отображение клуба, подробная информация о нем.
class DetailClubView(DetailView):
    template_name = 'collab/detail_club.html'
    model = ClubModel
    context_object_name = 'club'

    # Даем в контекст под ключом club объект модели ClubModel под текущим слагом.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Получение клуба по слагу
        context['club'] = get_club_by_slug(self.kwargs['slug'])
        return context


# Создание клуба.
class CreateClubView(CreateView):
    model = ClubModel
    template_name = 'collab/create_club.html'
    form_class = ClubModelForm
    success_url = reverse_lazy('collab:all_clubs')
    extra_context = {
        'title': 'Создать клуб',
        'menu_slug': 'create_club'
    }

    # Устанавливаем значение текущего пользователя для поля author.
    # Устанавливаем значение для слага на основе имени.
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.name)
        return super().form_valid(form)


# Профиль пользователя
class ProfileUser(TemplateView):
    template_name = 'collab/profile_user.html'

    extra_context = {
        'title': 'Личный кабинет',
        'menu_slug': 'profile_user'
    }

    # В контекс передает временный код для подтверждения Telegram аккаунта (код создается при регистрации пользователя).
    # В контекс передаем список клубов пользователя(где он является автором).
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['telegram_verif_code'] = self.request.user.telegram_verif_code

        # получение клуба на основе того, является ли текущий пользователь автором.
        context['my_clubs'] = ClubModel.objects.filter(author=self.request.user)

        return context


# Добавление пользователя в клуб при нажатии на кнопку.
def join_club_view(request, slug):
    # Получение клуба на основе слага
    club = get_club_by_slug(slug)
    club.request_team.add(request.user)

    # Отправляем уведомление о подаче заявки на участие в клубе.
    chat_id = get_author_by_slug(slug).telegram_chat_id
    message = f'Подана заявка на участие пользователем {request.user.username} в клуб {club.name}'
    try:
        send_message_to_user(chat_id, message)
    except:
        raise Http404()

    return redirect('collab:all_clubs')


# Отправка сообщения любому пользователю по pk.
# Дополнительно передается slug клуба, из которого происходит отправка.
class SendMsgView(FormView):
    template_name = 'collab/send_msg.html'
    form_class = SendMsgForm

    def form_valid(self, form):
        message = form.cleaned_data['message']
        message = f"""
        Вам пришло новое сообщение от пользователя {self.request.user} из клуба 
        {get_club_by_slug(self.kwargs['slug'])}.\nСообщение:\n{message}"""

        chat_id = get_user_model().objects.get(pk=self.kwargs['pk']).telegram_chat_id
        try:
            send_message_to_user(chat_id, message)
        except:
            raise Http404()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('collab:detail_club', kwargs={'slug': self.kwargs['slug']})


# Вывод всех заявок на участие в клубе. Только для админов.
class ListRequestTeamView(TemplateView):
    template_name = 'collab/list_confirm_team.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Передаем в контекст пользователей, которые подали заявку; клуб, в который подали заявку
        context['request_team'] = get_club_by_slug(self.kwargs['slug']).request_team.all()
        context['club'] = get_club_by_slug(self.kwargs['slug'])
        return context

collab/templates/collab/all_clubs.html
{% extends "collab/base/base.html" %}

{% block content %}


<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for club in all_clubs %}
        <div class="col">
            <div class="card h-100">
                <div class="card-body">
                    <a class="card-title text-decoration-none" href="{{ club.get_absolute_url }}">{{ club.name }}</a><br>
                    <a class="card-text text-decoration-none" href="{{ club.get_absolute_url }}">{{ club.desc|truncatechars:150 }}</a>
                </div>
                <div class="card-footer">
                    <small class="text-body-secondary">
                        {% for tag in club.tags.all %}
                        {{tag.name}}{% if not forloop.last %} {% endif %}
                        {% endfor %}
                    </small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

collab/templates/collab/create_club.html
{% extends "collab/base/base.html" %}


{% block content %}

<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
</div>

{% endblock %}

collab/templates/collab/detail_club.html
{% extends "collab/base/base.html" %}

{% block content %}

<div class="container">
<div class="card">
    <div class="card-header">
        <h1>{{ club.name }}</h1>
    </div>
    <div class="card-body">
        <p class="card-text">{{ club.desc }}</p>
        <p>{{ club.text|safe }}</p><br>

        <p>Требуются в команду: {{ club.required_team }}</p><br>

        <p>Теги:
        {% for tag in club.tags.all %}
        {{ tag.name }}
        {% endfor %}</p>

        <br>
        <h2>Автор</h2>
        <p>Имя: {{ club.author.first_name }}</p>
        <p>Фамилия: {{ club.author.last_name }}</p>
        <p>Возраст: {{ club.author.age }}</p>
        <p>Город: {{ club.author.city }}</p>
        <a class="btn btn-secondary" href="{% url 'collab:send_msg' slug=club.slug pk=club.author.pk %}">Написать автору</a>

        <br><br>
        <a class="btn btn-primary" href="{% url 'collab:join_club' slug=club.slug %}">Подать заявку на участие</a>
        <br><br>
        <a href="{% url 'collab:list_confirm_team' slug=club.slug %}">Подтвердить участников</a>

    </div>
</div>
</div>

{% endblock %}

collab/templates/collab/join_club.html
{% extends "collab/base/base.html" %}

{% block content %}


{% endblock %}

collab/templates/collab/list_confirm_team.html
{% extends "collab/base/base.html" %}


{% block content %}


{% for person in request_team %}

<div class="container">
<div class="alert alert-primary" role="alert">
    <p>{{ person.username }}</p>
    <p>{{ person.first_name }}</p>
    <p>{{ person.last_name }}</p>
    <p>{{ person.email }}</p>
    <p>{{ person.age }}</p>
    <p>{{ person.city }}</p>
    <p>{{ person.skills }}</p>
    <a href="{% url 'collab:send_msg' slug=club.slug pk=person.pk %}" class="btn btn-secondary">Написать</a><br><br>
    <a href="#" class="btn btn-success">Подтвердить</a>
</div>
    </div>
{% endfor %}


{% endblock %}

collab/templates/collab/profile_user.html
{% extends 'collab/base/base.html' %}

{% block content %}

<div class="container">
    <h2> Профиль</h2>
<p>{{ request.user}}</p>
<p>{{ request.user.first_name}}</p>
<p>{{ request.user.last_name}}</p>
<p>{{ request.user.email}}</p>
<p>{{ request.user.age}}</p>
<p>{{ request.user.city}}</p>

<h2>Мои клубы:</h2>
    {% for club in my_clubs %}
    <a href="{{ club.get_absolute_url }}">{{ club.name }}</a><br>
    {% endfor %}

    <br>
<h2>Телеграм бот</h2>
<a href="https://t.me/startup_clubs_bot?start={{telegram_verif_code}}" target="_blank">Ссылка на телеграм бот</a>

</div>
{% endblock %}

collab/templates/collab/send_msg.html
{% extends "collab/base/base.html" %}


{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
</div>

{% endblock %}